### ISSUE TITLE
ios_base::failbit set: iostream stream error

### ISSUE THREAD

**Issue by agirard2** [benjaminwand/Cherry-MX-keycaps#1]
Hello, I have tried to use this files.

> 10:49:54  Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> <class 'OSError'>: Invalid project file C:/Temp/pleasing.FCStd: ios_base::failbit set: iostream stream error

Freecad 
OS: Windows 10 (10.0)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.22846 (Git)
Build type: Release
Branch: master
Hash: 1f46b72491a0008384a6db4f2615a656249f6f08
Python version: 3.8.6
Qt version: 5.12.5
Coin version: 4.0.0
OCC version: 7.4.0
Locale: French/France (fr_FR)

I think that is a compatibility version problem but I am not able to fix it.

**Comment by benjaminwand** [comment]
Hi! Thanks for your feedback but I don't work with FreeCAD anymore, so no idea. Sorry!
Do you 'need' specific keycaps? It is not entirely impossibly that I'll model some in OpenSCAD at some point.

**Comment by agirard2** [comment]
OK Thank for you for this answer. I will draw it.
I have printed some keycaps from STL files and I would like to improve it.
